# Generated by Django 4.1.7 on 2023-03-15 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("myapp", "0006_toread"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="favorites",
            field=models.ManyToManyField(
                blank=True,
                default=None,
                related_name="favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="Toread",
        ),
    ]
