FROM python:3
ENV PYTHONUNBUFFERED 1
RUN apt-get update
RUN apt-get -y install cron 
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install requests
RUN touch /var/spool/cron/crontabs/root
RUN pip install django-cors-headers
RUN crontab -l
CMD python manage.py crontab add && service cron start && python manage.py runserver "0.0.0.0:8001"
