FROM python:3
ENV PYTHONUNBUFFERED 1
WORKDIR /app
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt
RUN pip install django-cors-headers
# RUN pip install axios dayjs jwt-decode react-router-dom@5.2.0
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]