# Generated by Django 4.1.7 on 2023-05-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connect", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="picture",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
